### ISSUE TITLE
ホーム画面で出てくるおすすめユーザをAge / Location / Fame rating / Tagsでソート＆フィルタリングしないといけない

### ISSUE THREAD

**Issue by TSUJI-Mariko** [Lala-pukuchan/matcha_mr#23]
![Screenshot from 2024-08-19 15-31-08](https://github.com/user-attachments/assets/e4b52b12-5e80-49fc-8aa3-57d13aef1c7a)
The suggestion list as well as the resulting list of a search must be
sortable and filterable by:
**Age / Location / Fame rating / Tags**

**Comment by TSUJI-Mariko** [comment]
The suggestion list as well as the resulting list of a search must be
sortable and filterable by:
**- Age.
- Location.
- Fame rating.
- Tags.**

**Comment by Lala-pukuchan** [comment]
@TSUJI-Mariko 
おすすめユーザーの取得方法を変更しました。
1. 年齢が自身の+-５歳
2. 住所が0~100km
3. fameRatingが20~100
4. 共通のタグ数1以上

その上で、絞り込み検索とソートをかけられます。
