### ISSUE TITLE
Reset Passwordメールで新パスワードが丸見え（一時的なログインキーにするなどしたほうが安全かも）

### ISSUE THREAD

**Issue by TSUJI-Mariko** [Lala-pukuchan/matcha_mr#30]
![Screenshot from 2024-08-19 16-16-35](https://github.com/user-attachments/assets/e38ad91f-5089-48b8-9de7-5eb342d96204)

**Comment by Lala-pukuchan** [comment]
@TSUJI-Mariko 
こちら新しいパスワードを発行しないと次回ログインができないですが、どういうことでしょう？
新しくパスワード変更画面を設ければ、一般的なサイトと同じ挙動になると思うので、特にこの部分は変更する必要がないと思います。
新しくパスワード変更画面を設ける必要はありますが、

**Comment by Lala-pukuchan** [comment]
一旦、テスト要件的に必須ではないので、クローズします。
必要であれば別途対応お願いします。
