### ISSUE TITLE
Websocketの接続が切れる

### ISSUE THREAD

**Issue by TSUJI-Mariko** [Lala-pukuchan/matcha_mr#40]
![スクリーンショット 2024-11-14 14 40 49](https://github.com/user-attachments/assets/88655797-b78f-4366-8e27-76e1b3df5f09)

**Search User ページ、Recommend Userページでユーザを表示すると、Websocket接続が確立されていない状態で、ソケットがクローズされてしまうときがあります。**

_WebSocket connection to 'ws:<URL>/socket.io/?EIO=4&transport=websocket' failed: WebSocket is closed before the connection is established._

![Screenshot from 2024-11-14 18-00-12](https://github.com/user-attachments/assets/e60550af-4ebc-46ed-9320-bc6b3e18af58)
**ユーザーを一度にロードしすぎると、接続が完全に切れます。**

# 自分で行った修正
**1. ユーザの表示数を絞り、Next / Prevボタンで往来可能にした**
/!\ Nextボタンを連打すると接続が切れます。
**2. Searchボタンを押すまでユーザを表示させない(Search Userのみ)**

# 現時点でできそうな対策
**- ユーザの表示数を絞る**
/!\ 表示数を4人に絞った場合はエラー表示を最大まで軽減できますが、表示数が少なすぎると思います。

**Comment by TSUJI-Mariko** [comment]
User表示数を管理している部分
現在は16人ずつ表示
https://github.com/Lala-pukuchan/matcha_mr/blob/3485b764ba5c2bde19dd6df3a64d6f5d9587e70a/client/src/app/components/userList.tsx#L42

**Comment by Lala-pukuchan** [comment]
APIで取得するデータ量が多すぎることで、サーバー側のリソースが不十分になり、websocketの接続が切れるということですね！

> User表示数を管理している部分
現在は16人ずつ表示

こちらに関して質問なのですが、フロントエンド側のコードを参照されていますが、ここの人数を変更することによって、表示人数が減るだけでなく、APIで取得するデータ量も減っていますか？（バックエンドからフロントエンドへ返却するデータ量も16人分に制限されていますかという意味です）

**Comment by TSUJI-Mariko** [comment]
はい。フロントエンド側で、バックエンド側で取得するデータ量も同量になるよう調節しています。
問題は、表示されているユーザのオンラインステータスを確認するためのwebsocketが表示されているユーザ数の倍数で動いてしまうことです。
16ユーザを表示させた場合、コンソールログ上で確認すると、ウェブソケットがユーザ最大でユーザ数の2倍近く接続されています。。

<img width="882" alt="スクリーンショット 2024-11-18 19 20 47" src="https://github.com/user-attachments/assets/929565d6-099e-4975-9bb7-ab148ece3b14">

<img width="880" alt="スクリーンショット 2024-11-18 19 21 37" src="https://github.com/user-attachments/assets/bd0dfdf5-edd1-49be-97ee-fc37e50c9604">

おそらく、フロントエンド側のuseEffectや依存関係が問題だと思います。

**Comment by Lala-pukuchan** [comment]
オンラインかを表示するのに、websocketを沢山繋ぎ直す必要はないと思いますが、表示人数分のwebsocketを繋いでいる理由は何かありますか？
（いろんな人がアクセスして、ユーザー一覧を見ると、膨大なwebsocketが繋がれることになっちゃいますね、websocketはあくまでも現時点でアクセスしている人のために作成すべきかと思います）
バックエンド側で、オンラインユーザーをカウントする用のリストを持てば、いちいち繋ぎ直す必要がないですが、持っていますでしょうか？
そちらのリストに接続がある毎にオンラインユーザーを追加して、接続が切れる毎に対象オンラインユーザーをリストから削除することで、常に現状のオンラインユーザーが誰なのか確認できます。

**Comment by TSUJI-Mariko** [comment]
修正したのでクローズします。
フロントエンド側の設計を変更しました。ウェブソケットをその都度接続し直すのではなく、シングルトンパターンを実装することで、ウェブソケット接続を一度だけ作成し、接続をアプリケーション全体で共有するようにしました。

ちなみに、バックエンド側で、オンラインユーザーをカウントする用のリストなどは用意していません。
